#-*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
    config.vm.define "vm1", primary: true do |vm1|
            vm1.vm.box = "centos/7"
            vm1.vm.hostname = "vm1"
            vm1.vm.provider "virtualbox" do |vb|
                vb.memory = "512"
                vb.cpus = "1"
            end
            vm1.vm.network "private_network", 
                ip: "192.168.12.10"
            vm1.vm.provision "ansible", run: "always", type: "ansible_local"  do |ansible|
          	ansible.become = true   
          	ansible.playbook = "/vagrant/playbooks/vm1.yml"
          end			
    end	

    config.vm.define "vm2", primary: true do |vm2|
        vm2.vm.box = "centos/7"
        vm2.vm.hostname = "vm2"
        vm2.vm.provider "virtualbox" do |vb|
            vb.memory = "512"
            vb.cpus = "1"
        end
        vm2.vm.network "private_network", 
            ip: "192.168.12.11"
        vm2.vm.provision "ansible", run: "always", type: "ansible_local"  do |ansible|
            ansible.become = true   
            ansible.playbook = "/vagrant/playbooks/vm2.yml"
        end		
    end	
end