# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    
    config.vm.box = "centos/8"
    config.vm.box_check_update = true
    config.vm.provider "virtualbox" do |vb|
        vb.memory = "512"
        vb.cpus = "1"
    end

    config.ssh.insert_key = "false"
   
    config.vm.provision "shell", inline: <<-SHELL
        echo "vagrant:vagrant" | chpasswd
        sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
        systemctl restart sshd.service
        # yum update -y
        echo "192.168.10.10 dc.otus.local" >> /etc/hosts
        echo "192.168.10.11 client.otus.local" >> /etc/hosts
        # yum install -y ipa-server ipa-server-dns
        # ipa-server-install < /vagrant/otvet.txt
        SHELL

    config.vm.define "dc", primary: true do |dc|
            dc.vm.provider "virtualbox" do |vbdc|
                vbdc.memory = "4096"
                vbdc.cpus = "4"
            end
            dc.vm.hostname = "dc.otus.local"
            dc.vm.network "private_network", ip: "192.168.10.10", virtualbox__intnet: true, name: "provision_net"
            dc.vm.network "private_network", ip: "13.13.13.13"
                       
         end

    config.vm.define "client", primary: true do |client|
            client.vm.hostname = "client.otus.local"
            client.vm.network "private_network", ip: "192.168.10.11", virtualbox__intnet: true, name: "provision_net"
         end

    config.vm.define "ansiblecontroller", primary: true do |ansiblecontroller|
            ansiblecontroller.vm.network "private_network", ip: "192.168.10.111", virtualbox__intnet: true, name: "provision_net"
            ansiblecontroller.vm.hostname = "ansiblecontroller"
                ansiblecontroller.vm.provision "ansible", run: "always", type: "ansible_local"  do |ansible|
                    ansible.playbook       = "provisioning/playbook.yml"
                    ansible.install        = true
                    ansible.verbose        = true
                    ansible.limit          = "all"
                    ansible.inventory_path = "hosts"
                    ansible.galaxy_role_file = "provisioning/requirements.yml"
                    ansible.galaxy_roles_path = "/etc/ansible/collections"
                    ansible.galaxy_command = "sudo ansible-galaxy collection install -r %{role_file} -p %{roles_path} --force"
                end
        end      
end    