# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
    config.vm.define "vm1", primary: true do |vm1|
          vm1.vm.box = "centos/8"
          vm1.vm.hostname = "vm1"
          vm1.vm.provider "virtualbox" do |vb|
                  vb.memory = "1024"
                  vb.cpus = "2"
              end
          vm1.vm.network "private_network", 
              virtualbox__intnet: true
          vm1.vm.provision "ansible", run: "always", type: "ansible_local"  do |ansible|
          	ansible.become = true   
          	ansible.playbook = "/vagrant/playbooks/vm1.yml"
          end			
      end	

      config.vm.define "vm2", primary: true do |vm2|
        vm2.vm.box = "centos/8"
        vm2.vm.hostname = "vm2"
        vm2.vm.provider "virtualbox" do |vb|
                vb.memory = "1024"
                vb.cpus = "2"
            end
        vm2.vm.network "private_network", 
            virtualbox__intnet: true
        vm2.vm.provision "ansible", run: "always", type: "ansible_local"  do |ansible|
        	ansible.become = true
        	ansible.playbook = "/vagrant/playbooks/vm2.yml"
        end			
    end

    config.vm.define "vm3", primary: true do |vm3|
        vm3.vm.box = "centos/8"
        vm3.vm.hostname = "vm3"
        vm3.vm.provider "virtualbox" do |vb|
                vb.memory = "1024"
                vb.cpus = "2"
            end
        vm3.vm.network "private_network", 
            virtualbox__intnet: true
        vm3.vm.provision "ansible", run: "always", type: "ansible_local"  do |ansible|
        	ansible.become = true
        	ansible.playbook = "/vagrant/playbooks/vm3.yml"
        end			
    end

end