# -*- mode: ruby -*-
# vi: set ft=ruby :

$scripthosts = <<-SCRIPT

echo "vagrant:vagrant" | chpasswd
sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
systemctl restart sshd.service

SCRIPT

$scriptans = <<-SCRIPT

echo "vagrant:vagrant" | chpasswd
sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
systemctl restart sshd.service

apt update -y
apt install -y ansible sshpass
cp /vagrant/ansible.cfg /etc/ansible/
SCRIPT

Vagrant.configure("2") do |config|
 
	config.vm.define "acontr", primary: true do |acontr|
		acontr.vm.box = "debian/buster64"
		acontr.vm.hostname = "acontr"
			acontr.vm.provider "virtualbox" do |vb|
				vb.memory = "1024"
				vb.cpus = "2"
			end
		acontr.vm.network "private_network", ip: "192.168.34.10"
		acontr.vm.provision :shell, inline: $scriptans
		acontr.vm.synced_folder ".", "/vagrant", type: "smb", 
			smb_password: "vagrant", smb_username: "vagrant"
		acontr.ssh.insert_key = false
		
	end	
 
	config.vm.define "web" do |web|
		web.vm.box = "debian/buster64"
		web.vm.hostname = "web"
			web.vm.provider "virtualbox" do |vb|
				vb.memory = "512"
				vb.cpus = "1"
			end
		web.vm.network "private_network", ip: "192.168.34.11"
		web.vm.provision :shell, inline: $scripthosts
		web.vm.synced_folder ".", "/vagrant", disabled: true
		web.ssh.insert_key = false
	end	
 
	config.vm.define "log" do |log|
		log.vm.box = "debian/buster64"
		log.vm.hostname = "log"
			log.vm.provider "virtualbox" do |vb|
				vb.memory = "512"
				vb.cpus = "1"
			end
		log.vm.network "private_network", ip: "192.168.34.12"
		log.vm.provision :shell, inline: $scripthosts
		log.vm.synced_folder ".", "/vagrant", disabled: true
		log.ssh.insert_key = false
	end	
 
 
end
