MACHINES = {
  :ubuntuzfs => {
        :box_name => "ubuntu/focal64",
	    :disks => {
		:hdd1 => {
			:dfile => './hdd1.vdi',
			:size => 5000,
			:port => 2
		},
		:hdd2 => {
            :dfile => './hdd2.vdi',
            :size => 5000,
			:port => 3
		},
		:hdd3 => {
            :dfile => './hdd3.vdi',
            :size => 5000,
			:port => 4
		},
    }

		
  },
}

Vagrant.configure("2") do |config|
    config.vm.boot_timeout = 1200
	MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s
	
	      box.vm.provider :virtualbox do |vb|
            	  vb.customize ["modifyvm", :id, "--memory", "4096"]
				  vb.customize ["modifyvm", :id, "--cpus", "4"]
                  
				  needsController = false
		          
				  boxconfig[:disks].each do |dname, dconf|
			         
					 unless File.exist?(dconf[:dfile])
				     vb.customize ['createhd', '--filename', dconf[:dfile], '--variant', 'Fixed', '--size', dconf[:size]]
                     needsController =  true
                     end
					 
		          end
                  
				  if needsController == true
                     
					 #vb.customize ["storagectl", :id, "--name", "SATA2", "--add", "sata" ]
                     boxconfig[:disks].each do |dname, dconf|
                         vb.customize ['storageattach', :id,  '--storagectl', 'SCSI', '--port', dconf[:port], '--device', 0, '--type', 'hdd', '--medium', dconf[:dfile]]
                     end
					 
                  end
          end
	
 
  config.vm.provision "shell", inline: <<-SHELL
  apt-get update
  apt install zfsutils-linux
  SHELL
        end
    end
end