# -*- mode: ruby -*-
# vi: set ft=ruby :
MACHINES = {
	:server => {
		:box_name => "centos/7",
		:cpus => 2,
		:memory => 2048,
		#:ip_addr => '10.1.1.10',
		:path => './raid.sh',
		:disks => {
		:sata1 => {
			:dfile => './sata1.vdi',
			:size => 250,
			:port => 1
		},
		:sata2 => {
			:dfile => './sata2.vdi',
			:size => 250, # Megabytes
			:port => 2
		},
		:sata3 => {
			:dfile => './sata3.vdi',
			:size => 250,
			:port => 3
		},
		:sata4 => {
			:dfile => './sata4.vdi',
			:size => 250, # Megabytes
			:port => 4
		},
		:sata5 => {
			:dfile => './sata5.vdi',
			:size => 250, # Megabytes
			:port => 5
		},
	}
	},
}

Vagrant.configure("2") do |config|
	config.vm.boot_timeout = 1200
	MACHINES.each do |boxname, boxconfig|

		config.vm.define boxname do |box|
			box.vm.host_name = boxname.to_s
			box.vm.box = boxconfig[:box_name]
			box.vm.host_name = boxname.to_s
			#box.vm.network "private_network", ip: boxconfig[:ip_addr]

			box.vm.provider :virtualbox do |vb|
				vb.memory = boxconfig[:memory]
				vb.cpus = boxconfig[:cpus]
				needsController = false
				boxconfig[:disks].each do |dname, dconf|
					unless File.exist?(dconf[:dfile])
					vb.customize ['createhd', '--filename', dconf[:dfile], '--variant', 'Fixed', '--size', dconf[:size]]
						needsController =  true
					end

				end
				if needsController == true
					vb.customize ["storagectl", :id, "--name", "SATA", "--add", "sata" ]
					boxconfig[:disks].each do |dname, dconf|
					vb.customize ['storageattach', :id,  '--storagectl', 'SATA', '--port', dconf[:port], '--device', 0, '--type', 'hdd', '--medium', dconf[:dfile]]
					end
				end
			end
			

		box.vm.provision	:shell,	:path => boxconfig[:path]

		#config.vm.provision "shell", inline: <<-SHELL
		
		#SHELL
		end
	end
end
