# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
 
	config.vm.define "test", primary: true do |test|
		test.vm.box = "centos/7"
		test.vm.hostname = "test"
		test.vm.provider "virtualbox" do |vb|
				vb.memory = "1024"
				vb.cpus = "2"
			end
		test.vm.network "private_network", ip: "192.168.34.10",
			virtualbox__intnet: true,
			name: "onlyVM"
		test.vm.provision "ansible", run: "always", type: "ansible_local"  do |ansible|
			ansible.become = true
			ansible.galaxy_role_file = "requirements.yml"
			ansible.galaxy_roles_path = "/etc/ansible/collections"
			ansible.galaxy_command = "sudo ansible-galaxy collection install -r %{role_file} -p %{roles_path} --force"
			ansible.playbook = "playbook.yml"
		end
			
	end	

end
